name: Deployment

on: 
  push:
    branches:
      - master
      - 'test/**'

jobs:
  deployment:
    uses: Minnek-Digital-Studio/bigcommerce-action/.github/workflows/deployment.yml@master
    secrets: inherit
    
