name: Deployment to Production

on:
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'

jobs:
  deployment-prod:
    uses: Minnek-Digital-Studio/jira-action/.github/workflows/jira-deployment-prod.yml@master
    secrets:
      CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.JIRA_CLIENT_SECRET }}
