name: Theme Check

on:
  pull_request:
    branches: [ develop ]

jobs:
  theme_check:
    uses: Minnek-Digital-Studio/bigcommerce-action/.github/workflows/theme-check.yml@master
    secrets: inherit
